</div>
	
	
	
		<div class="postmetadata">
		
			
			</div> 

		
		<!-- ?php comments_template(); ? -->
		
		
		</div>

		
		


	
	
	
	<div id="navigation">
			<div class="fleft"></div>
					<div class="fright"> </div>
	</div>
			
	

		
	

		</div>
	</div> <!-- eof main -->

<!-- begin sidebar -->

<!-- end sidebar -->

	





<div style="clear:both;"></div>
</div>
</div> <!-- eo content -->

	<div id="footer">
	<div id="footer-inner">
	
	</div>
	</div>

	
	<div id="credit">

		<p>Alibi3col theme by <a href="http://themocracy.com/"><img style="vertical-align:-7px;" src="/static/alibi3col/images/themocracy_icon.gif" /></a><a href="http://themocracy.com/">Themocracy</a></p>
	</div>
	
</div>
</div>
</div>
</div>

</body>
</html>


