
<h2>Donate to the Helping Hand Fund</h2>

<p>You can make a donation to the Helping Hand Fund using the PayPal button below.</p>

<form action="https://www.paypal.com/cgi-bin/webscr" method="post">
<p>
Pay £ <input type="text" name="amount" size="6" \>
to BiCon 2010 (paypal:paypal@bicon2010.org.uk)
<input type="hidden" name="notify_url" value="https://secure.10icb.org/registration/paypal-ipn.php">
<input type="hidden" name="return" value="https://secure.10icb.org/registration/">
<input type="hidden" name="image_url" value="https://secure.10icb.org/bicon/logo.jpg">
<input type="hidden" name="custom" value="0">
<input type="hidden" name="cmd" value="_xclick">
<input type="hidden" name="business" value="paypal@bicon2010.org.uk">
<input type="hidden" name="item_name" value="Bicon Helping Hand Fund donation">
<input type="hidden" name="item_number" value="id:0">
<input type="hidden" name="no_shipping" value="2">
<input type="hidden" name="no_note" value="1">
<input type="hidden" name="currency_code" value="GBP">
<input type="hidden" name="lc" value="GB">
<input type="hidden" name="bn" value="PP-BuyNowBF">
<input type="image" src="https://www.paypal.com/en_US/i/btn/x-click-but23.gif" border="0" name="submit" alt="Make payments with PayPal - it's fast, free and secure!">
<img alt="" border="0" src="https://www.paypal.com/en_US/i/scr/pixel.gif" width="1" height="1">
</p>
</form>
