<!-- Helping Hand: YES -->

<tr>
<td align=right>How much assistance do you require?</td>
<td>
<input type="text" name="hhrequest" value="<?= $person->hhrequest ?>">
</td>
</tr>

<tr>
<td align=right>Why do you require assistance?</td>
<td>
<input type="text" name="hhreason" value="<?= $person->hhreason ?>">
</td>
</tr>

<tr>
<td align=right>Any other information you can give us will help
us to deal with your application more quickly and efficiently</td>
<td>
<input type="text" name="otherhhinfo" value="<?= $person->otherhhinfo ?>">
</td>
</tr>

