<?php

if ( $totalremain < 150 ) {

    $surcharge = 2.5;

} else {

    $surcharge = 4;

}

$paypaltot = $totalremain + $surcharge;

?>


<h2>Payment options</h2>

<p>
We're very sorry - we've had to temporarily disable payment by paypal.
We hope to reestablish it very quickly indeed, and will post a note on
the site when it's returned.
</p>

<h2>Pay by cheque</h2>

<p>
If you'd like to pay by <strong>cheque</strong> or
<strong>postal order</strong>, please make it payable to
<strong>Bifest</strong> (<em>not</em> BiCon) and send it,
with a printout of this
page OR your name, address and booking ID to:
</p>

<p>
Bicon 2007,<br>
BM Bicon,<br>
London<br>
WC1N 3XX<br>
UK
</p>

